### ISSUE TITLE
versioning .md is not clear

### ISSUE THREAD

**Issue by koresar** [cloverfield-tools/prod-module-boilerplate#39]
The details are a bit washed out here: https://github.com/cloverfield-tools/prod-module-boilerplate/blob/master/docs/contributing/versions/index.md

Put it this way:
* What's that? - single sentence
* Why? - purpose
* Details - mvp, and the rest...

Put up TOC on top as well.

Otherwise people won't be reading it. :)

**Comment by ericelliott** [comment]
* [x] Add Sections
* [ ] Add Links

:question: Do the sections look good?

**Comment by koresar** [comment]
Looks good.
If you are thinking of simple Table Of Contents (with anchors) you can check this out: https://raw.githubusercontent.com/stampit-org/stampit/master/ADVANCED_EXAMPLES.md

**Comment by koresar** [comment]
You can also add in the "What" section - `these are code names for major releases`.

**Comment by ericelliott** [comment]
Re Doctoc, see: #40

**Comment by ericelliott** [comment]
Should be good now. Let me know if it still needs any work. =)
