### ISSUE TITLE
Add Doctoc to build

### ISSUE THREAD

**Issue by ericelliott** [cloverfield-tools/prod-module-boilerplate#40]
## Blocking #39 

[Doctoc](https://github.com/thlorenz/doctoc)

See also https://github.com/cloverfield-tools/prod-module-boilerplate/issues/39

**Comment by ericelliott** [comment]
@nkbt want to take this?

cc @koresar

**Comment by nkbt** [comment]
Should be quite easy. Unless anyone picks it up before, will do it first tonight.

**Comment by ericelliott** [comment]
:+1:

**Comment by nkbt** [comment]
Done, #42
