### ISSUE TITLE
`npm run build:doc` doesn't work with Windows

### ISSUE THREAD

**Issue by forresst** [cloverfield-tools/prod-module-boilerplate#51]
## Summary
`npm run build:doc` doesn't work in Windows

## Steps to reproduce
Run in Windows Terminal : `npm run build:doc`

## Expected behavior
Update markdown files with TOC (Table of contents)

## Actual behavior

doctoc not properly recovered parameters: doctoc not doing its job

## Screenshot
![doctoc](https://cloud.githubusercontent.com/assets/163352/9246471/fddc8e72-41ab-11e5-88c0-96a1a7bed8f6.png)

## References
Originally filed in npm-scripts-example repo: https://github.com/keithamus/npm-scripts-example/issues/5

**Comment by ericelliott** [comment]
@nkbt Is this change already in [cf-package](https://github.com/cloverfield-tools/cf-package)?

**Comment by nkbt** [comment]
No, it is not. I made a copy of template before this one was merged.
