### ISSUE TITLE
`npm run build:min` doesn't work with Windows

### ISSUE THREAD

**Issue by forresst** [cloverfield-tools/prod-module-boilerplate#53]
## Summary
`npm run build:min` doesn't work in Windows

## Steps to reproduce
Run in Windows Terminal : `npm run build:min`

## Expected behavior
Execute webpack with the environnement variables `NODE_ENV=production` and `MINIFY=1`

## Actual behavior
webpack don't execute because Windows does not accept the definition of environment variables in this way

## Screenshot
![env](https://cloud.githubusercontent.com/assets/163352/9252232/a08417aa-41d7-11e5-85ef-3f950f7bc947.png)

## References
Originally filed in react-redux-universal-hot-example repo: https://github.com/erikras/react-redux-universal-hot-example/pull/71

**Comment by ericelliott** [comment]
This boilerplate is graduating to a [Cloverfield scaffold](https://github.com/cloverfield-tools/cf-package/issues/2) to make it easier to reuse. Please make this fix there. =)

**Comment by forresst** [comment]
Done : https://github.com/cloverfield-tools/cf-package/issues/13
